### ISSUE TITLE
0.4.0 re-introduced issue #10

### ISSUE THREAD

**Issue by Chris-Softrams** [derberg/global-workflows-support#26]
See  https://github.com/derberg/global-workflows-support/issues/10

**Comment by derberg** [comment]
@Chris-Softrams can you provide some logs or something. Action now uses REST API, not GraphQL to get list of repos (because of easier pagination) and look at: https://github.com/derberg/global-workflows-support/blob/main/lib/api-calls.js#L63. According to docs, this is where info about default branch is stored, or root of response under `default_branch`

**Comment by derberg** [comment]
I'm closing this issue as there are no details. I tried to find issues while working on https://github.com/derberg/global-workflows-support/releases/tag/v0.6.0 and manual testing, but all was good. Please create new issue with logs
